"""add_user_type.

Revision ID: 8347c7c38d2e
Revises: 1e2ee4035887
Create Date: 2025-03-14 15:47:41.473480

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8347c7c38d2e"
down_revision: str | None = "1e2ee4035887"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_type", sa.CHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###
