"""auto_increment_resource_id.

Revision ID: ac40ca0db4f7
Revises: 9513a23adc62
Create Date: 2025-03-13 18:03:41.429198

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac40ca0db4f7"
down_revision: str | None = "9513a23adc62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.alter_column(
            "id",
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.alter_column(
            "id",
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )
    # ### end Alembic commands ###
