"""fix_resource_usage_type.

Revision ID: 1e2ee4035887
Revises: ac40ca0db4f7
Create Date: 2025-03-13 18:11:45.077197

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e2ee4035887"
down_revision: str | None = "ac40ca0db4f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.alter_column(
            "total_run_time",
            existing_type=sa.BIGINT(),
            type_=sa.Float(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.alter_column(
            "total_run_time",
            existing_type=sa.Float(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
