"""add_tool_calls.

Revision ID: 77c3a2c91298
Revises: 5a7f6b9f900b
Create Date: 2025-04-15 14:29:03.544236

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB as PGJSONB
from sqlalchemy.dialects.sqlite import JSON as SQLiteJSON  # noqa: N811

# revision identifiers, used by Alembic.
revision: str = "77c3a2c91298"
down_revision: str | None = "5a7f6b9f900b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages") as batch_op:
        batch_op.add_column(
            sa.Column(
                "tool_calls",
                PGJSONB().with_variant(SQLiteJSON(), "sqlite"),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages") as batch_op:
        batch_op.drop_column("tool_calls")
    # ### end Alembic commands ###
