"""adjust_message_id.

Revision ID: 421cc5247b83
Revises: 1e2ee4035887
Create Date: 2025-03-14 14:14:43.748373

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "421cc5247b83"
down_revision: str | None = "1e2ee4035887"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.Text(),
            existing_nullable=False,
            unique=True,
        )

    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.drop_constraint("resource_usage_message_id_fk", type_="foreignkey")

    with op.batch_alter_table("messages") as batch_op:
        batch_op.drop_index("messages_message_id_index")
        batch_op.drop_constraint("messages_message_id_unique", type_="unique")
        batch_op.drop_column("message_id")

    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.Text(),
            existing_nullable=False,
            unique=True,
        )
        batch_op.drop_index("idx_resource_usage_message_id")
        batch_op.create_foreign_key(
            "resource_usage_message_id_fk",
            "messages",
            ["id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("message_id")

    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column("user_type", sa.CHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("user_type")

    with op.batch_alter_table("messages") as batch_op:
        batch_op.add_column(sa.Column("message_id", sa.TEXT(), nullable=True))
        batch_op.create_unique_constraint(
            "messages_message_id_unique",
            ["message_id"],
        )
        batch_op.create_index(
            "messages_message_id_index",
            ["message_id"],
            unique=False,
            postgresql_using="hash",
        )

    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.add_column(sa.Column("message_id", sa.TEXT(), nullable=True))
        batch_op.drop_constraint("resource_usage_message_id_fk", type_="foreignkey")
        batch_op.create_foreign_key(
            "resource_usage_message_id_fk",
            "messages",
            ["message_id"],
            ["message_id"],
            ondelete="CASCADE",
        )
        batch_op.create_index(
            "idx_resource_usage_message_id",
            ["message_id"],
            unique=False,
        )

    # ### end Alembic commands ###
